# baseurl: /jinyao2009.github.io 
title: Jin Yao's Website
# subtitle: Content-centric blogging
author: Jin Yao
simple_search: http://google.com/search
description: Jin's personal website
name: Jin Yao
markdown: Kramdown
kramdown:  
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments #pygments rouge
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'Run_in_local.md', 'examples']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: emacs
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/jinyao2009.github.com/